# Generated by Django 3.2.4 on 2021-10-05 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_appointment_doctor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
